version = 0.1

[default.deploy.parameters]
stack_name = "sam-app"
resolve_s3 = true
s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "AwsAccessKeyId=\"AKIA4ECPWV4BXBL6RUWG\" AwsSecretAccessKey=\"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\" TwilioPhoneNumber=\"+14155238886\" SupabaseUrl=\"https://onpkpvfwyblglsyzaohe.supabase.co\" S3BucketName=\"qila-scam-detection-images\""
image_repositories = []
