AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'B2B Pilot Async Processing with Lambda and SNS'

Parameters:
  Environment:
    Type: String
    Default: prod
    AllowedValues:
      - prod
      - staging
    Description: Deployment environment (prod or staging)
  TwilioAccountSid:
    Type: String
    Description: Twilio Account SID
    NoEcho: true
  TwilioAuthToken:
    Type: String
    Description: Twilio Auth Token
    NoEcho: true
  TwilioPhoneNumber:
    Type: String
    Description: "Your Twilio WhatsApp number (format: whatsapp:+1234567890)"
  ResponseFeedbackTemplate:
    Type: String
    Description: Response and Feedback template
  SupabaseUrl:
    Type: String
    Description: Supabase project URL
    Default: ""
  SupabaseKey:
    Type: String
    Description: Supabase service role key
    NoEcho: true
    Default: ""
  AiApiKey:
    Type: String
    Description: OpenAI API key for scam analysis
    NoEcho: true
  VirusTotalApiKey:
    Type: String
    Description: VirusTotal API key for URL scanning
    NoEcho: true
  GoogleSafeBrowsingKey:
    Type: String
    Description: Google Safe Browsing API key
    NoEcho: true
  S3BucketName:
    Type: String
    Description: S3 bucket for storing uploaded images
  ApiKey:
    Type: String
    Description: Optional API key for webapp/mobile clients
    Default: ""
    NoEcho: true

Globals:
  Function:
    Timeout: 300
    Runtime: python3.12
    MemorySize: 512
    Environment:
      Variables:
        ENVIRONMENT: !Ref Environment
        TWILIO_ACCOUNT_SID: !Ref TwilioAccountSid
        TWILIO_AUTH_TOKEN: !Ref TwilioAuthToken
        TWILIO_PHONE_NUMBER: !Ref TwilioPhoneNumber
        RESPONSE_FEEDBACK_TEMPLATE: !Ref ResponseFeedbackTemplate
        SUPABASE_URL: !Ref SupabaseUrl
        SUPABASE_KEY: !Ref SupabaseKey
        AI_API_KEY: !Ref AiApiKey
        VIRUSTOTAL_API_KEY: !Ref VirusTotalApiKey
        GOOGLE_SAFE_BROWSING_KEY: !Ref GoogleSafeBrowsingKey
        S3_BUCKET_NAME: !Ref S3BucketName
        API_KEY: !Ref ApiKey

Resources:

  # Main SNS Topic for near-instant message delivery
  MessageTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub "b2b-pilot-messages-${Environment}"
      DisplayName: "B2B Pilot Message Processing Topic"
      Tags:
        - Key: Application
          Value: B2B-Pilot
        - Key: Purpose
          Value: WhatsAppProcessing

  # Dead Letter Queue for failed messages (SNS -> Lambda failures)
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub "b2b-pilot-messages-dlq-${Environment}"
      MessageRetentionPeriod: 1209600
      Tags:
        - Key: Application
          Value: B2B-Pilot
        - Key: Purpose
          Value: FailedMessages

  # Webhook Lambda
  WebhookFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "b2b-pilot-webhook-handler-${Environment}"
      CodeUri: webhook-handler/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MessageTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MessageTopic.TopicName
      Events:
        WebhookApi:
          Type: Api
          Properties:
            Path: /authenticity_check
            Method: post
            RestApiId: !Ref WebhookApi

  # API Gateway
  WebhookApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub "b2b-pilot-webhook-api-${Environment}"
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST, OPTIONS'"
        AllowHeaders: "'Content-Type,X-Twilio-Signature,X-Client-Type,Authorization,X-Api-Key,X-Amz-Date,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        ApiKeyRequired: false
      EndpointConfiguration:
        Type: REGIONAL

  # Processor Lambda
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "b2b-pilot-background-processor-${Environment}"
      CodeUri: background-processor/
      Handler: handler.lambda_handler
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt DeadLetterQueue.Arn
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic: !Ref MessageTopic
            # Optional: Add filter policy for different message types
            # FilterPolicy:
            #   client_type:
            #     - whatsapp
            #     - webapp
            #     - mobile

  # Presigned URL Lambda
  PresignedUrlFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "b2b-pilot-presigned-url-${Environment}"
      CodeUri: presigned-url/
      Handler: handler.lambda_handler
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref S3BucketName
      Events:
        PresignedUrlApi:
          Type: Api
          Properties:
            Path: /presigned_url
            Method: post
            RestApiId: !Ref WebhookApi
        PresignedUrlGetApi:
          Type: Api
          Properties:
            Path: /presigned_url
            Method: get
            RestApiId: !Ref WebhookApi
        PresignedUrlOptions:
          Type: Api
          Properties:
            Path: /presigned_url
            Method: options
            RestApiId: !Ref WebhookApi

  # Stale Message Processor Lambda
  # Processes WhatsApp message groups that didn't reach aggregation thresholds
  StaleMessageProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "b2b-pilot-stale-message-processor-${Environment}"
      CodeUri: stale-message-processor/
      Handler: handler.lambda_handler
      Timeout: 30
      MemorySize: 256
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref MessageTopic
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt MessageTopic.TopicName
      Events:
        ScheduleEvent:
          Type: Schedule
          Properties:
            Name: !Sub "stale-message-processor-schedule-${Environment}"
            Description: "Run the stale message processor every minute"
            Schedule: rate(1 minute)
            Enabled: false  # Disabled - now using Step Functions

  # Step Functions State Machine for Stale Message Processing
  StaleMessageProcessorStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: !Sub "b2b-pilot-stale-processor-${Environment}"
      RoleArn: !GetAtt StepFunctionsExecutionRole.Arn
      DefinitionString: !Sub |
        {
          "Comment": "Loop to invoke stale message processor Lambda every 10 seconds",
          "StartAt": "InvokeStaleProcessor",
          "States": {
            "InvokeStaleProcessor": {
              "Type": "Task",
              "Resource": "arn:aws:states:::lambda:invoke",
              "Parameters": {
                "FunctionName": "${StaleMessageProcessorFunction.Arn}",
                "Payload": {
                  "source": "step-functions"
                }
              },
              "Retry": [
                {
                  "ErrorEquals": ["Lambda.ServiceException", "Lambda.AWSLambdaException", "Lambda.SdkClientException"],
                  "IntervalSeconds": 2,
                  "MaxAttempts": 3,
                  "BackoffRate": 2
                }
              ],
              "Next": "Wait10Seconds"
            },
            "Wait10Seconds": {
              "Type": "Wait",
              "Seconds": 10,
              "Next": "CheckContinue"
            },
            "CheckContinue": {
              "Type": "Choice",
              "Choices": [
                {
                  "Variable": "$.stopExecution",
                  "BooleanEquals": true,
                  "Next": "Done"
                }
              ],
              "Default": "InvokeStaleProcessor"
            },
            "Done": {
              "Type": "Succeed"
            }
          }
        }
      Tags:
        - Key: Application
          Value: B2B-Pilot
        - Key: Purpose
          Value: StaleMessageProcessing

  # IAM Role for Step Functions
  StepFunctionsExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "b2b-pilot-step-functions-role-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: InvokeLambdaPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'lambda:InvokeFunction'
                Resource: !GetAtt StaleMessageProcessorFunction.Arn

  # EventBridge Rule to start Step Functions execution
  # WARNING: This will create multiple concurrent executions if left enabled
  # RECOMMENDED: Start the Step Functions execution manually once, then disable this rule
  # Or keep it disabled and only enable if the execution stops unexpectedly
  StaleProcessorScheduleRule:
    Type: AWS::Events::Rule
    Properties:
      Name: !Sub "stale-processor-trigger-${Environment}"
      Description: "Trigger Step Functions state machine for stale message processing"
      ScheduleExpression: "rate(1 hour)"
      State: DISABLED  # Disabled by default - start execution manually
      Targets:
        - Arn: !GetAtt StaleMessageProcessorStateMachine.Arn
          RoleArn: !GetAtt EventBridgeStepFunctionsRole.Arn
          Id: StaleProcessorTarget

  # IAM Role for EventBridge to start Step Functions
  EventBridgeStepFunctionsRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "b2b-pilot-eventbridge-stepfunctions-${Environment}"
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: StartStepFunctionsPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'states:StartExecution'
                Resource: !GetAtt StaleMessageProcessorStateMachine.Arn

  # CloudWatch Alarms
  SNSFailedDeliveryAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "b2b-pilot-sns-failed-delivery-${Environment}"
      AlarmDescription: Alert when SNS messages fail to deliver to Lambda
      MetricName: NumberOfNotificationsFailed
      Namespace: AWS/SNS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: TopicName
          Value: !GetAtt MessageTopic.TopicName

  DLQAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "b2b-pilot-dlq-messages-${Environment}"
      AlarmDescription: Alert when messages enter the DLQ
      MetricName: ApproximateNumberOfMessagesVisible
      Namespace: AWS/SQS
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 1
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: QueueName
          Value: !GetAtt DeadLetterQueue.QueueName

  ProcessorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "b2b-pilot-processor-errors-${Environment}"
      AlarmDescription: Alert when processor Lambda errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 1
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref ProcessorFunction

  StaleProcessorErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub "b2b-pilot-stale-processor-errors-${Environment}"
      AlarmDescription: Alert when stale message processor Lambda errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 10
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref StaleMessageProcessorFunction

Outputs:
  WebhookUrl:
    Description: Twilio webhook URL
    Value: !Sub "https://${WebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/authenticity_check"
  TopicArn:
    Description: SNS Topic ARN
    Value: !Ref MessageTopic
  DLQUrl:
    Description: Dead Letter Queue URL
    Value: !Ref DeadLetterQueue
  PresignedUrlEndpoint:
    Description: Presigned URL API endpoint
    Value: !Sub "https://${WebhookApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/presigned_url"
  StaleMessageProcessorFunction:
    Description: Stale Message Processor Lambda Function ARN
    Value: !GetAtt StaleMessageProcessorFunction.Arn
  StaleProcessorStateMachine:
    Description: Step Functions State Machine ARN for Stale Message Processing
    Value: !GetAtt StaleMessageProcessorStateMachine.Arn
  StaleProcessorStateMachineUrl:
    Description: Step Functions State Machine Console URL
    Value: !Sub "https://console.aws.amazon.com/states/home?region=${AWS::Region}#/statemachines/view/${StaleMessageProcessorStateMachine}"
